In [1]:
import os
import cv2
import matplotlib.pyplot as plt
import  face_recognition
import PIL.Image
import PIL.ImageDraw
import pandas as pd
from openpyxl.workbook import Workbook

In [30]:
path="Faces"
images=os.listdir(path)
j=-1
print(images)
for img in images:
    img="Faces/"+img
    j=j+1
    images[j]=img

cols= ["left_A","left_B","left_C","left_ear","right_A","right_B","right_C","right_ear","AVG_EAR","Class"]
df = pd.DataFrame([], columns = cols)

['c10.jpg', 'c11.jpg', 'c12.jpg', 'c13.jpg', 'c14.jpg', 'c15.jpg', 'c16.jpg', 'c17.jpg', 'c18.jpg', 'c19.jpg', 'c2.jpg', 'c20.jpg', 'c21.jpg', 'c22.jpg', 'c23.jpg', 'c24.jpg', 'c25.jpg', 'c26.jpg', 'c27.jpg', 'c28.jpg', 'c29.jpg', 'c3.jpg', 'c30.jpg', 'c31.jpg', 'c32.jpg', 'c34.jpg', 'c35.jpg', 'c36.jpg', 'c37.jpg', 'c38.jpg', 'c39.jpg', 'c4.jpg', 'c40.jpg', 'c41.jpg', 'c42.jpg', 'c43.jpg', 'c44.jpg', 'c45.jpg', 'c46.jpg', 'c47.jpg', 'c48.jpg', 'c49.jpg', 'c5.jpg', 'c50.jpg', 'c51.jpg', 'c52.jpg', 'c53.jpg', 'c54.jpg', 'c55.jpg', 'c56.jpg', 'c57.jpg', 'c59.jpg', 'c6.jpg', 'c60.jpg', 'c61.jpg', 'c62.jpg', 'c63.jpg', 'c64.jpg', 'c65.jpg', 'c66.jpg', 'c67.jpg', 'c68.jpg', 'c69.jpg', 'c7.jpg', 'c70.jpg', 'c71.jpg', 'c72.jpg', 'c73.jpg', 'c74.jpg', 'c75.jpg', 'c8.jpg', 'c9.jpg', 'o1.jpg', 'o10.jpg', 'o11.jpg', 'o12.jpg', 'o13.jpg', 'o14.jpg', 'o15.jpg', 'o16.jpg', 'o17.jpg', 'o18.jpg', 'o19.jpg', 'o2.jpg', 'o20.jpg', 'o21.jpg', 'o22.jpg', 'o23.jpg', 'o24.jpg', 'o25.jpg', 'o26.jpg', 'o27.jpg', 'o28.jpg', 'o29.jpg', 'o3.jpg', 'o30.jpg', 'o31.jpg', 'o32.jpg', 'o34.jpg', 'o35.jpg', 'o36.jpg', 'o37.jpg', 'o38.jpg', 'o39.jpg', 'o4.jpg', 'o40.jpg', 'o41.jpg', 'o42.jpg', 'o43.jpg', 'o44.jpg', 'o45.jpg', 'o46.jpg', 'o47.jpg', 'o48.jpg', 'o49.jpg', 'o5.jpg', 'o50.jpg', 'o51.jpg', 'o52.jpg', 'o53.jpg', 'o54.jpg', 'o55.jpg', 'o56.jpg', 'o57.jpg', 'o58.jpg', 'o59.jpg', 'o6.jpg', 'o60.jpg', 'o61.jpg', 'o62.jpg', 'o63.jpg', 'o64.jpg', 'o65.jpg', 'o67.jpg', 'o68.jpg', 'o69.jpg', 'o7.jpg', 'o70.jpg', 'o71.jpg', 'o72.jpg', 'o73.jpg', 'o74.jpg', 'o75.jpg', 'o8.jpg', 'o9.jpg']

In [31]:
from scipy.spatial import distance as dist
i=0 
cls=0
for image in images:
    input_image = face_recognition.load_image_file(image)
    face_landmarks = face_recognition.face_landmarks(input_image)
    landmark1 = face_landmarks[0].get('left_eye')
    landmark2 = face_landmarks[0].get('right_eye')
    left_A = dist.euclidean(landmark1[1], landmark1[5])
    left_B = dist.euclidean(landmark1[2], landmark1[4])
    left_C = dist.euclidean(landmark1[0], landmark1[3])
    left_ear = (left_A + left_B) / (2.0 * left_C)
    right_A = dist.euclidean(landmark2[1], landmark2[5])
    right_B = dist.euclidean(landmark2[2], landmark2[4])
    right_C = dist.euclidean(landmark2[0], landmark2[3])
    right_ear = (right_A + right_B) / (2.0 * right_C)
    AVG_EAR= ( right_ear + left_ear )/2
    if(AVG_EAR<0.25):
        cls=0
    else: cls=1
    out=[left_A,left_B,left_C,left_ear,right_A,right_B,right_C,right_ear,AVG_EAR,cls]
    i=i+1
    df.loc[i]=out

In [32]:
df

,left_A,left_B,left_C,left_ear,right_A,right_B,right_C,right_ear,AVG_EAR,Class
1,2.000000,2.000000,12.000000,0.166667,2.000000,2.236068,12.000000,0.176503,0.171585,0.0
2,2.000000,3.000000,16.000000,0.156250,2.236068,3.000000,16.031220,0.163308,0.159779,0.0
3,1.000000,1.000000,14.035669,0.071247,1.000000,1.000000,13.000000,0.076923,0.074085,0.0
4,2.000000,3.162278,26.076810,0.098982,2.000000,3.000000,26.019224,0.096083,0.097532,0.0
5,1.000000,2.000000,15.033296,0.099779,2.236068,1.414214,15.033296,0.121407,0.110593,0.0
...,...,...,...,...,...,...,...,...,...,...
141,12.369317,12.369317,32.756679,0.377612,13.038405,13.038405,20.223748,0.644708,0.511160,1.0
142,16.000000,13.000000,58.034473,0.249851,14.000000,14.000000,58.034473,0.241236,0.245544,0.0
143,9.000000,10.000000,33.015148,0.287747,9.055385,9.000000,38.052595,0.237242,0.262495,1.0
144,7.000000,7.071068,21.023796,0.334646,6.082763,7.000000,20.099751,0.325446,0.330046,1.0
145,5.000000,4.000000,15.033296,0.299336,4.123106,5.000000,14.317821,0.318593,0.308964,1.0

In [33]:
with pd.ExcelWriter(r'C:\Users\5CD034CN3L\Desktop\eye_dataset.xlsx')as writer:
    df.to_excel(writer,sheet_name='eye')